export const metadatMappings: any = {
    '0': { label: 'RF_RADIO_CONNECTED', type: 'connection', location: 'server' },
    '1': { label: 'SYNCHRONIZE_RADIO', type: 'connection', location: 'server' },
    '2': { label: 'ROLL', type: 'gyro', location: 'rover' },
    '3': { label: 'PITCH', type: 'gyro', location: 'rover' },
    '4': { label: 'YAW', type: 'gyro', location: 'rover' },
    '5': { label: 'SWAY', type: 'accelerometer', location: 'rover' },
    '6': { label: 'HEAVE', type: 'accelerometer', location: 'rover' },
    '7': { label: 'SURGE', type: 'accelerometer', location: 'rover' },
    '8': { label: 'OIL_PRESSURE', type: 'oil_pressure_switch', location: 'rover' },
    '9': { label: 'KNOCK', type: 'knock_sensor', location: 'rover' },
    '10': { label: 'STEERING_ANGLE', type: 'rotary_encoder', location: 'rover' },
    '11': { label: 'CHASIS_DEFLECTION', type: 'strain_guage', location: 'rover' },
    '12': { label: 'SUSPENSION_DEFLECTION', type: 'strain_guage', location: 'rover' },
    '13': { label: 'FUEL_PRESSURE', type: 'pressure_transducer', location: 'rover' },
    '14': { label: 'LATITUDE', type: 'gps', location: 'rover' },
    '15': { label: 'LONGITUDE', type: 'gps', location: 'rover' },
    '16': { label: 'EXAUST_TEMPRATURE', type: 'thermistor', location: 'rover' },
    '17': { label: 'OIL_PRESSURE_ADVANCED', type: 'pressure_transducer', location: 'rover' },
    '18': { label: 'DIFFUSER_PITOT_TUBE', type: 'pressure_transducer', location: 'rover' },
    '19': { label: 'DIFFUSER_PRESSURE_TAPPINGS', type: 'pressure_transducer', location: 'rover' },
    '20': { label: 'FL_WHEEL_SPEED', type: 'hall_effect', location: 'rover' },
    '21': { label: 'FR_WHEEL_SPEED', type: 'hall_effect', location: 'rover' },
    '22': { label: 'BL_WHEEL_SPEED', type: 'hall_effect', location: 'rover' },
    '23': { label: 'BR_WHEEL_SPEED', type: 'hall_effect', location: 'rover' },
    '24': { label: 'FL_SUSPENSION_TRAVEL', type: 'linear_potentiometer', location: 'rover' },
    '25': { label: 'FR_SUSPENSION_TRAVEL', type: 'linear_potentiometer', location: 'rover' },
    '26': { label: 'BL_SUSPENSION_TRAVEL', type: 'linear_potentiometer', location: 'rover' },
    '27': { label: 'BR_SUSPENSION_TRAVEL', type: 'linear_potentiometer', location: 'rover' },
    '28': { label: 'FR_RIDE_HIGHT', type: 'ultra_sonic', location: 'rover' },
    '29': { label: 'FL_RIDE_HIGHT', type: 'ultra_sonic', location: 'rover' },
    '30': { label: 'BR_RIDE_HIGHT', type: 'ultra_sonic', location: 'rover' },
    '31': { label: 'BL_RIDE_HIGHT', type: 'ultra_sonic', location: 'rover' },
    '32': { label: 'DRIVER_INSTRUCTIONS', type: 'logic', location: 'rover' },

    '48': { label: 'MOVEMENT_ENABLED', type: 'motor', location: 'rover' },
    '49': { label: 'MOVEMENT_SPEED', type: 'motor', location: 'rover' },
    '50': { label: 'MOTOR_ONE_ENABLED', type: 'motor', location: 'rover' },
    '51': { label: 'MOTOR_ONE_FORWARD', type: 'motor', location: 'rover' },
    '52': { label: 'MOTOR_ONE_SPEED', type: 'motor', location: 'rover' },
    '53': { label: 'MOTOR_TWO_ENABLED', type: 'motor', location: 'rover' },
    '54': { label: 'MOTOR_TWO_FORWARD', type: 'motor', location: 'rover' },
    '55': { label: 'MOTOR_TWO_SPEED', type: 'motor', location: 'rover' },
    '56': { label: 'MOTOR_THREE_ENABLED', type: 'motor', location: 'rover' },
    '57': { label: 'MOTOR_THREE_FORWARD', type: 'motor', location: 'rover' },
    '58': { label: 'MOTOR_THREE_SPEED', type: 'motor', location: 'rover' },
    '59': { label: 'MOTOR_FOUR_ENABLED', type: 'motor', location: 'rover' },
    '60': { label: 'MOTOR_FOUR_FORWARD', type: 'motor', location: 'rover' },
    '61': { label: 'MOTOR_FOUR_SPEED', type: 'motor', location: 'rover' },

    '62': { label: 'ARM_YAW', type: 'servo', location: 'arm' },
    '63': { label: 'ARM_PITCH_1', type: 'servo', location: 'arm' },
    '64': { label: 'ARM_PITCH_2', type: 'servo', location: 'arm' },
    '65': { label: 'ARM_ROLL', type: 'servo', location: 'arm' },

    '66': { label: 'CLAW_ENABLED', type: 'motor', location: 'arm' },
    '67': { label: 'CLAW_FORWARD', type: 'motor', location: 'arm' },
    '68': { label: 'CLAW_SPEED', type: 'motor', location: 'arm' },
    '69': { label: 'CLAW_STATUS', type: 'motor', location: 'arm' },

    '70': { label: 'ARM_ENABLED', type: 'logic', location: 'arm' },
    '71': { label: 'ARM_MANULE_OVERIDE', type: 'logic', location: 'arm' },
    '72': { label: 'ARM_STATUS', type: 'logic', location: 'arm' },
    '73': { label: 'ARM_NEXT_STATUS', type: 'logic', location: 'arm' }
};
